import React from 'react';
import Head from 'next/head';
import styles from './Home.module.scss';
import dynamic from 'next/dynamic';
const Editor = dynamic(() => import('../components/Editor'), { ssr: false });

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Task : Ekank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2 className="text-center my-5">Editor Assignment</h2>
      <Editor />
    </div>
  );
}

export async function getStaticProps() {
  return {
    props: {},
  };
}
